version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: private-chat-server_server_1
      APP_PORT: 8000
      NODE_ENV: production
    
  server:
    image: privatechatprotocol/private-chat-server:1.2.0
    user: "1000:1000"
    init: true
